apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: omegaargo-refresh-app
spec: 
  destination: 
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm/nginx
    repoURL: https://github.com/nkorojoseph/omegaargo
    targetRevision: main
